// 模型菜单与运行时能力的共同目录。scripts/catalog.py 按 JSON 读取此模块。
// 来源：v1.0.11 已维护的 API 元数据及官方接口核对；策略字段由项目维护。
var MODEL_CATALOG = {
    "eleven_flash_v2_5": {
        "title": "Flash v2.5 — 快速、省额度（32 语言，推荐划词朗读）",
        "order": 0,
        "hidden": false,
        "deprecated": false,
        "charLimit": 40000,
        "transport": "http",
        "sendLanguageCode": true,
        "languages": [
            "ar",
            "bg",
            "cs",
            "da",
            "de",
            "el",
            "en",
            "es",
            "fi",
            "fil",
            "fr",
            "hi",
            "hr",
            "hu",
            "id",
            "it",
            "ja",
            "ko",
            "ms",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "ru",
            "sk",
            "sv",
            "ta",
            "tr",
            "uk",
            "vi",
            "zh"
        ],
        "settings": {
            "style": false,
            "use_speaker_boost": false
        }
    },
    "eleven_v4": {
        "title": "v4 — 最新高音质、情感丰富（90+ 语言）",
        "order": 1,
        "hidden": false,
        "deprecated": false,
        "charLimit": 10000,
        "transport": "http",
        "sendLanguageCode": true,
        "languages": [
            "af",
            "am",
            "ar",
            "hy",
            "as",
            "ast",
            "az",
            "be",
            "bn",
            "bs",
            "bg",
            "my",
            "yue",
            "ca",
            "ceb",
            "hr",
            "cs",
            "da",
            "nl",
            "en",
            "et",
            "fil",
            "fi",
            "fr",
            "ff",
            "gl",
            "ka",
            "de",
            "el",
            "gu",
            "ha",
            "he",
            "hi",
            "hu",
            "is",
            "id",
            "it",
            "ja",
            "jv",
            "kam",
            "kn",
            "kk",
            "ko",
            "ky",
            "lo",
            "lv",
            "ln",
            "lt",
            "lg",
            "lb",
            "mk",
            "ms",
            "ml",
            "mt",
            "zh",
            "mi",
            "mr",
            "mn",
            "ne",
            "nb",
            "oc",
            "or",
            "ps",
            "fa",
            "pl",
            "pt",
            "pa",
            "ro",
            "ru",
            "sr",
            "sn",
            "sd",
            "sk",
            "sl",
            "so",
            "ckb",
            "es",
            "sw",
            "sv",
            "tg",
            "ta",
            "te",
            "th",
            "tr",
            "uk",
            "ur",
            "uz",
            "vi",
            "cy",
            "wo",
            "zu"
        ],
        "settings": {
            "style": false,
            "speed": false,
            "use_speaker_boost": false
        },
        "settingsOverrides": {
            "style": false,
            "speed": false,
            "use_speaker_boost": false
        },
        "languageOverrides": {
            "yue": "yue",
            "no": "nb",
            "nb": "nb"
        }
    },
    "eleven_v4_turbo": {
        "title": "v4 Turbo — 高表现力、低延迟（90+ 语言）",
        "order": 2,
        "hidden": false,
        "deprecated": false,
        "charLimit": 10000,
        "transport": "dialogueWebSocket",
        "sendLanguageCode": true,
        "languages": [
            "af",
            "am",
            "ar",
            "hy",
            "as",
            "ast",
            "az",
            "be",
            "bn",
            "bs",
            "bg",
            "my",
            "yue",
            "ca",
            "ceb",
            "hr",
            "cs",
            "da",
            "nl",
            "en",
            "et",
            "fil",
            "fi",
            "fr",
            "ff",
            "gl",
            "ka",
            "de",
            "el",
            "gu",
            "ha",
            "he",
            "hi",
            "hu",
            "is",
            "id",
            "it",
            "ja",
            "jv",
            "kam",
            "kn",
            "kk",
            "ko",
            "ky",
            "lo",
            "lv",
            "ln",
            "lt",
            "lg",
            "lb",
            "mk",
            "ms",
            "ml",
            "mt",
            "zh",
            "mi",
            "mr",
            "mn",
            "ne",
            "nb",
            "oc",
            "or",
            "ps",
            "fa",
            "pl",
            "pt",
            "pa",
            "ro",
            "ru",
            "sr",
            "sn",
            "sd",
            "sk",
            "sl",
            "so",
            "ckb",
            "es",
            "sw",
            "sv",
            "tg",
            "ta",
            "te",
            "th",
            "tr",
            "uk",
            "ur",
            "uz",
            "vi",
            "cy",
            "wo",
            "zu"
        ],
        "settings": {
            "style": false,
            "speed": false,
            "use_speaker_boost": false
        },
        "localLimit": true,
        "settingsOverrides": {
            "style": false,
            "speed": false,
            "use_speaker_boost": false
        },
        "languageOverrides": {
            "yue": "yue",
            "no": "nb",
            "nb": "nb"
        }
    },
    "eleven_multilingual_v2": {
        "title": "Multilingual v2 — 音质最稳、情感自然（29 语言）",
        "order": 3,
        "hidden": false,
        "deprecated": false,
        "charLimit": 10000,
        "transport": "http",
        "sendLanguageCode": false,
        "languages": [],
        "settings": {
            "style": true,
            "use_speaker_boost": true
        }
    },
    "eleven_v3": {
        "title": "v3 — 表现力强、支持 70+ 语言（较慢、较贵）",
        "order": 4,
        "hidden": false,
        "deprecated": false,
        "charLimit": 5000,
        "transport": "http",
        "sendLanguageCode": true,
        "languages": null,
        "settings": {
            "style": false,
            "use_speaker_boost": false
        }
    },
    "eleven_v3_conversational": {
        "title": "v3 Conversational — v3 的低延迟版、表现力强（70+ 语言）",
        "order": 5,
        "hidden": false,
        "deprecated": false,
        "charLimit": 5000,
        "transport": "http",
        "sendLanguageCode": true,
        "languages": null,
        "settings": {
            "style": false,
            "use_speaker_boost": true
        }
    },
    "eleven_flash_v2": {
        "title": "Flash v2",
        "order": 90,
        "hidden": true,
        "deprecated": false,
        "charLimit": 30000,
        "transport": "http",
        "sendLanguageCode": true,
        "languages": [
            "en"
        ],
        "settings": {
            "style": false,
            "use_speaker_boost": false
        },
        "englishOnly": true
    },
    "eleven_turbo_v2_5": {
        "title": "Turbo v2.5",
        "order": 91,
        "hidden": true,
        "deprecated": true,
        "charLimit": 40000,
        "transport": "http",
        "sendLanguageCode": true,
        "languages": [
            "ar",
            "bg",
            "cs",
            "da",
            "de",
            "el",
            "en",
            "es",
            "fi",
            "fil",
            "fr",
            "hi",
            "hr",
            "hu",
            "id",
            "it",
            "ja",
            "ko",
            "ms",
            "nl",
            "no",
            "pl",
            "pt",
            "ro",
            "ru",
            "sk",
            "sv",
            "ta",
            "tr",
            "uk",
            "vi",
            "zh"
        ],
        "settings": {
            "style": false,
            "use_speaker_boost": false
        }
    },
    "eleven_turbo_v2": {
        "title": "Turbo v2",
        "order": 92,
        "hidden": true,
        "deprecated": true,
        "charLimit": 30000,
        "transport": "http",
        "sendLanguageCode": true,
        "languages": [
            "en"
        ],
        "settings": {
            "style": false,
            "use_speaker_boost": false
        },
        "englishOnly": true
    }
};

exports.MODEL_CATALOG = MODEL_CATALOG;
